env:
  node: true
  commonjs: true
  es2021: true
globals:
  fetch: false
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
  object-curly-spacing:
    - error
    - always
