env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:cypress/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - cypress
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  arrow-parens:
    - warn
    - as-needed
  no-unused-vars: warn
  object-curly-spacing:
    - error
    - always
